# Publish all joint states ------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Velocity Controllers ----------------------------------
  joint_back_left_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_back_left_wheel
    pid: {p: 0.1, i: 0.5, d: 0.1}

  joint_back_right_wheel_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_back_right_wheel
    pid: {p: 0.1, i: 0.5, d: 0.1}

#Position controllers  ----------------------------------
  joint_front_left_hinge_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_front_left_hinge
    pid: {p: 0.1, i: 0.5, d: 0.1}

  joint_front_right_hinge_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_front_right_hinge
    pid: {p: 0.1, i: 0.5, d: 0.1}


